### ISSUE TITLE
Configuration Guideline

### ISSUE THREAD

**Issue by ozkar99** [elalmirante/elalmirante#2]
## configuration example (yaml based):

```yaml
servers:
  server-1:
    host: host1
    key:  key1
    tags:
      - project1

  server-2:
    host: host2
    key: key2
    tags:
      - project2

  server-3:
    host: host3
    key: key
    tags:
      - project1
```

## query language:
its a coma based language, based on the tags.
you deploy based on tags, you can use `!` to negate a tag and a special case for `*` to deploy everything.
when you parse the configuration each server gets automatilly asigned its name as tag.

some examples:

`project1` should deploy server-1 and server-3
`server-3` should deploy only server-3
`project1,!server-3` should deploy tags with project1 minus server-3

the query language should respect left-to-right for priorities, something like:

`*,!abc`

would deploy everything but servers with tag !abc

something with:

`!abc,*`

would deploy everything.
